#!/bin/bash
#PBS -P ox63
#PBS -q normal
#PBS -N analyse_variant
#PBS -l walltime=48:00:00
#PBS -l mem=128GB
#PBS -l jobfs=256GB
#PBS -l ncpus=1
#PBS -l wd
#PBS -l storage=gdata/ox63+scratch/ox63
#PBS -M m.naeini@garvan.org.au


module load R/4.4.2

Rscript /scratch/ox63/mn4616/analyse_variants_chr.R \
  --chr "chr22" \
  --mode "All" \
  --vcf_rdata /scratch/ox63/mn4616/snv_indel.RData \
  --output_dir /scratch/ox63/mn4616/plots_indel
