#!/bin/bash
#PBS -P ox63
#PBS -q normal
#PBS -N combine_autosomes
#PBS -l walltime=48:00:00
#PBS -l mem=192GB
#PBS -l jobfs=256GB
#PBS -l ncpus=1
#PBS -l wd
#PBS -l storage=gdata/ox63+scratch/ox63
#PBS -M m.naeini@garvan.org.au

module load R/4.4.2

INPUT_DIR="/scratch/ox63/mn4616/plots_indel"
OUTPUT_FILE="/scratch/ox63/mn4616/plots_indel/All_autosomes_combined_VCF_df.RData"

Rscript "/scratch/ox63/mn4616/combine_rdata.R" \
  --input_dir "$INPUT_DIR" \
  --output_file "$OUTPUT_FILE"
